### ISSUE TITLE
vcgencmd missing and causing error

### ISSUE THREAD

**Issue by eleff210** [gdombiak/OctoPrint-OctoPod#132]
Receiving an issue after the OctoPod plugin initializes while using a Raspi 4 4GB.  I have my OctoPrint running within a docker container but I don't believe that to be the issue.  The error messages suggest that the install of VCGENCMD might be required and is not initialized during install of the plugin. 

Error Message below:
2021-12-08 11:28:10,584 - octoprint.plugins.octopod - INFO - OctoPod loaded!,
Initializing GcodePositionProcessor V1.0.1 - Copyright (C) 2019 Brad Hochgesang...Python 3+ Detected...complete
,
2021-12-08 11:28:10,791 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid,
Exception in thread Thread-33:,
Traceback (most recent call last):,
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 667, in run,
self.process = p = Popen(self.args, **self.kwargs),
File "/usr/local/lib/python3.8/subprocess.py", line 858, in init,
self.execute_child(args, executable, preexec_fn, close_fds,,
File "/usr/local/lib/python3.8/subprocess.py", line 1704, in execute_child,
Exception in thread Thread-35:,
Traceback (most recent call last):,
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 667, in run,
self.process = p = Popen(self.args, **self.kwargs),
File "/usr/local/lib/python3.8/subprocess.py", line 858, in init,
raise child_exception_type(errno_num, err_msg, err_filename),
FileNotFoundError: [Errno 2] No such file or directory: '/opt/vc/bin/vcgencmd',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
File "/usr/local/lib/python3.8/threading.py", line 932, in bootstrap_inner,
self.execute_child(args, executable, preexec_fn, close_fds,,
File "/usr/local/lib/python3.8/subprocess.py", line 1704, in execute_child,
self.run(),
File "/usr/local/lib/python3.8/site-packages/octoprint/util/init.py", line 1338, in run,
raise child_exception_type(errno_num, err_msg, err_filename),
FileNotFoundError: [Errno 2] No such file or directory: '/opt/vc/bin/vcgencmd',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
File "/usr/local/lib/python3.8/threading.py", line 932, in bootstrap_inner,
self.function(*self.args, **self.kwargs),
File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_navbartemp/init.py", line 68, in update_soc_temp,
temp = self.sbc.check_soc_temp(),
File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_navbartemp/libs/sbc.py", line 73, in check_soc_temp,
p = run(self.temp_cmd, stdout=Capture()),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1480, in run,
self.run(),
File "/usr/local/lib/python3.8/site-packages/octoprint/util/init.py", line 1338, in run,
p.run(input=input, async=async),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1087, in run,
self.function(*self.args, **self.kwargs),
File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octopod/init.py", line 381, in update_soc_temp,
self.run_node(node, input=input, async=False),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1205, in run_node,
self.soc_temp_notifications.check_soc_temp(self.settings),
File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octopod/soc_temp_notifications.py", line 32, in check_soc_temp,
result = getattr(self, method)(node, input, async),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1351, in run_command_node,
temp = float(self.sbc.check_soc_temp()),
File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octopod/libs/sbc.py", line 79, in check_soc_temp,
p = run(self.temp_cmd, stdout=Capture()),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1480, in run,
node.cmd.run(input=input, async=async),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 670, in run,
raise ValueError('Command not found: %s' % self.args[0]),
ValueError: Command not found: /opt/vc/bin/vcgencmd,
p.run(input=input, async=async),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1087, in run,
self.run_node(node, input=input, async_=False),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1205, in run_node,
result = getattr(self, method)(node, input, async_),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 1351, in run_command_node,
node.cmd.run(input=input, async_=async_),
File "/usr/local/lib/python3.8/site-packages/sarge/init.py", line 670, in run,
raise ValueError('Command not found: %s' % self.args[0]),
ValueError: Command not found: /opt/vc/bin/vcgencmd,

**Comment by andrewgribben** [comment]
I'm also experiencing this with Octprint running as a docker container on Ubuntu running on a Pi 4.
