### ISSUE TITLE
Migration error thrown on fresh install with latest OctoPi install.

### ISSUE THREAD

**Issue by Pizzahd88** [gdombiak/OctoPrint-OctoPod#97]
2021-08-03 20:52:59,767 - octoprint - ERROR - Error while trying to migrate settings for plugin octopod, ignoring it
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 512, in init_settings_plugin_config_migration_and_cleanup
    implementation._identifier, implementation
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 496, in settings_plugin_config_migration_and_cleanup
    settings_migrator(settings_version, stored_version)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octopod/__init__.py", line 129, in on_settings_migrate
    if current <= 2:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

**Comment by Pizzahd88** [comment]
Afterwards I cannot connect my IOS devices, nofitifications does not work.
![image](https://user-images.githubusercontent.com/29568847/128070882-3041c186-ce91-415f-9a66-4562f995ffb9.png)

**Comment by Pizzahd88** [comment]
More info on my boot:
2021-08-03 20:52:56,243 - octoprint.startup - INFO - ******************************************************************************
2021-08-03 20:52:56,246 - octoprint.startup - INFO - Starting OctoPrint 1.6.1
2021-08-03 20:52:56,246 - octoprint.startup - INFO - ******************************************************************************
2021-08-03 20:52:56,507 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity changed from offline to online
2021-08-03 20:52:56,550 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2021-08-03 20:52:56,551 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2021-08-03 20:52:56,551 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2021-08-03 20:52:56,561 - octoprint.startup - INFO - Blacklist processing done, adding 12 blacklisted plugin versions: roomtemp (any), GcodeEditor (0.1.1), GcodeEditor (0.2.0), GcodeEditor (0.2.1), GcodeEditor (0.2.2), GcodeEditor (0.2.3), GcodeEditor (0.2.4), GcodeEditor (0.2.5), GcodeEditor (0.2.6), GcodeEditor (0.2.8), gcodeleveling (0.1.0), gcodeleveling (0.1.1)
2021-08-03 20:52:56,594 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2021-08-03 20:52:57,785 - octoprint.startup - INFO - Added settings overlay from plugin dashboard
2021-08-03 20:52:57,803 - octoprint.plugin.core - INFO - Found 29 plugin(s) providing 29 mixin implementations, 71 hook handlers
2021-08-03 20:52:57,972 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2021-08-03 20:52:57,979 - octoprint.server - INFO - Intermediary server started
2021-08-03 20:52:57,995 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2021-08-03 20:52:58,241 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2021-08-03 20:52:58,244 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: "Need(method='role', value='plugin_action_command_notification_show')")
2021-08-03 20:52:58,245 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: "Need(method='role', value='plugin_action_command_notification_clear')")
2021-08-03 20:52:58,245 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: "Need(method='role', value='plugin_action_command_prompt_interact')")
2021-08-03 20:52:58,245 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: "Need(method='role', value='plugin_announcements_read')")
2021-08-03 20:52:58,245 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: "Need(method='role', value='plugin_announcements_manage'), Need(method='role', value='plugin_announcements_read')")
2021-08-03 20:52:58,246 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: "Need(method='role', value='plugin_appkeys_admin')")
2021-08-03 20:52:58,246 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: "Need(method='role', value='plugin_backup_access')")
2021-08-03 20:52:58,246 - octoprint.server - INFO - Added new permission from plugin dashboard: PLUGIN_DASHBOARD_ADMIN (needs: "Need(method='role', value='plugin_dashboard_admin')")
2021-08-03 20:52:58,246 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: "Need(method='role', value='plugin_firmware_check_display')")
2021-08-03 20:52:58,247 - octoprint.server - INFO - Added new permission from plugin klipper: PLUGIN_KLIPPER_CONFIG (needs: "Need(method='role', value='plugin_klipper_admin')")
2021-08-03 20:52:58,247 - octoprint.server - INFO - Added new permission from plugin klipper: PLUGIN_KLIPPER_MACRO (needs: "Need(method='role', value='plugin_klipper_admin')")
2021-08-03 20:52:58,247 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: "Need(method='role', value='plugin_logging_manage')")
2021-08-03 20:52:58,247 - octoprint.server - INFO - Added new permission from plugin pi_support: PLUGIN_PI_SUPPORT_STATUS (needs: "Need(method='role', value='plugin_pi_support_check')")
2021-08-03 20:52:58,248 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2021-08-03 20:52:58,248 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: "Need(method='role', value='plugin_pluginmanager_manage'), Need(method='role', value='plugin_pluginmanager_install')")
2021-08-03 20:52:58,249 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: "Need(method='role', value='plugin_softwareupdate_check')")
2021-08-03 20:52:58,249 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: "Need(method='role', value='plugin_softwareupdate_update')")
2021-08-03 20:52:58,249 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: "Need(method='role', value='plugin_softwareupdate_configure')")
2021-08-03 20:52:58,307 - octoprint.printer.standard - INFO - Using print time estimator provided by PrintTimeGenius
2021-08-03 20:52:58,909 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2021-08-03 20:52:59,493 - octoprint.util.pip - INFO - Version of pip is 20.3.3
2021-08-03 20:52:59,495 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-08-03 20:52:59,495 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-08-03 20:52:59,623 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2021-08-03 20:52:59,750 - octoprint.plugin.core - INFO - Initialized 29 plugin implementation(s)
2021-08-03 20:52:59,767 - octoprint - ERROR - Error while trying to migrate settings for plugin octopod, ignoring it
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 512, in init_settings_plugin_config_migration_and_cleanup
    implementation._identifier, implementation
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/__init__.py", line 496, in settings_plugin_config_migration_and_cleanup
    settings_migrator(settings_version, stored_version)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_octopod/__init__.py", line 129, in on_settings_migrate
    if current <= 2:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
2021-08-03 20:52:59,772 - octoprint.plugin.core - INFO - 29 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Bed Visualizer (1.1.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_bedlevelvisualizer
|  BLTouch Plugin (0.3.4) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Dashboard (1.18.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_dashboard
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  DisplayLayerProgress Plugin (1.26.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_DisplayLayerProgress
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  File Check (2021.2.23) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  FileManager (0.1.6) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_filemanager
|  Firmware Check (2021.5.31) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
|  Fullscreen Plugin (0.0.6) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_fullscreen
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  OctoKlipper (0.3.8.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_klipper
|  Octolapse (0.4.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_octolapse
|  OctoPod Plugin (0.3.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_octopod
|  Pi Support Plugin (2021.8.2) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  PrintTimeGenius Plugin (2.2.8) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintTimeGenius
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  Tab Order (0.5.12) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_taborder
|  Themeify (1.2.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_themeify
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2021-08-03 20:52:59,806 - octoprint.environment - INFO - Detected environment is Python 3.7.3 under Linux (linux). Details:
|  hardware:
|    cores: 4
|    freq: 1500.0
|    ram: 3959984128
|  os:
|    bits: 32
|    id: linux
|    platform: linux
|  plugins:
|    pi_support:
|      model: Raspberry Pi 4 Model B Rev 1.1
|      octopi_version: 0.18.0
|      throttle_state: '0x0'
|  python:
|    pip: 20.3.3
|    version: 3.7.3
|    virtualenv: /home/pi/oprint
2021-08-03 20:52:59,819 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2021-08-03 20:52:59,848 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2021-08-03 20:53:00,519 - octoprint.server - INFO - Shutting down intermediary server...
2021-08-03 20:53:01,006 - octoprint.server - INFO - Intermediary server shut down
2021-08-03 20:53:01,007 - octoprint.events - INFO - Processing startup event, this is our first event
2021-08-03 20:53:01,007 - octoprint.events - INFO - Adding 2 events to queue that were held back before startup event
2021-08-03 20:53:01,010 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2021-08-03 20:53:01,013 - octoprint.server - INFO - Autoconnect on startup is configured, trying to connect to the printer...
2021-08-03 20:53:01,015 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2021-08-03 20:53:01,052 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2021-08-03 20:53:01,191 - octoprint.server - INFO - Trying to connect to configured serial port /tmp/printer
2021-08-03 20:53:01,276 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial connection"
2021-08-03 20:53:01,278 - octoprint.util.comm - INFO - Serial detection: Performing autodetection with 7 port/baudrate candidates: /tmp/printer@115200, /tmp/printer@250000, /tmp/printer@230400, /tmp/printer@57600, /tmp/printer@38400, /tmp/printer@19200, /tmp/printer@9600
2021-08-03 20:53:01,278 - octoprint.util.comm - INFO - Serial detection: Trying port /tmp/printer, baudrate 115200
2021-08-03 20:53:01,279 - octoprint.util.comm - INFO - Connecting to port /tmp/printer, baudrate 115200
2021-08-03 20:53:01,300 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2021-08-03 20:53:01,303 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2021-08-03 20:53:01,305 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2021-08-03 20:53:01,312 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2021-08-03 20:53:01,336 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-08-03 20:53:01,356 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Operational"
2021-08-03 20:53:01,364 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-08-03 20:53:01,374 - octoprint.plugins.klipper.debug - INFO - Connected to host via /tmp/printer @0bps
2021-08-03 20:53:01,431 - octoprint.plugins.klipper.debug - INFO - Firmware version: v0.9.1-621-gdafb74e3
2021-08-03 20:53:01,431 - octoprint.util.comm - INFO - Printer reports firmware name "Klipper"
2021-08-03 20:53:01,432 - octoprint.util.comm - INFO - Detected Klipper firmware, enabling relevant features for issue free communication
2021-08-03 20:53:02,477 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2021-08-03 20:53:02,489 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-08-03 20:53:02,489 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-08-03 20:53:02,670 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2021-08-03 20:53:02,677 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2021-08-03 20:53:03,486 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._http._tcp.local.' for _http._tcp.local.
2021-08-03 20:53:04,294 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._octoprint._tcp.local.' for _octoprint._tcp.local.
2021-08-03 20:53:04,319 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2021-08-03 20:53:04,353 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2021-08-03 20:53:04,418 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:XXX.XXX.X.XX
2021-08-03 20:53:04,533 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2021-08-03 20:53:04,756 - octoprint.server.util.flask - INFO - Passively logging in user XXXXXX from ::ffff:XXX.XXX.X.XX
2021-08-03 20:53:04,756 - octoprint.access.users - INFO - Logged in user: XXXXXX
2021-08-03 20:53:05,090 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python3 -m pip" as command to invoke pip
2021-08-03 20:53:05,092 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python3.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2021-08-03 20:53:05,092 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-08-03 20:53:05,112 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 23.9GB. That is considered sufficient for updating.
2021-08-03 20:53:05,400 - octoprint.plugins.bedlevelvisualizer - INFO - OctoPrint-BedLevelVisualizer loaded!
2021-08-03 20:53:05,400 - octoprint.plugins.dashboard - INFO - Dashboard started
2021-08-03 20:53:05,422 - octoprint.plugins.octopod - INFO - OctoPod loaded!
2021-08-03 20:53:05,466 - octoprint.plugins.themeify - INFO - Themeify initialized.
2021-08-03 20:53:06,051 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2021-08-03 20:53:06,349 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'base_url': 'http://octopi.localdomain/', 'path': '/', 'query_string': 'l10n=en'}

**Comment by gdombiak** [comment]
Hey @Pizzahd88 , sorry I missed this ticket. Are you still seeing this error?
